services:
  db:
    image: postgres:15.6
    container_name: paperless-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - /mnt/truenas/appdata/paperless/db:/var/lib/postgresql/data
      - /mnt/truenas/appdata/paperless/db-backups:/backups

    labels:
      - "diun.enable=false"

  redis:
    image: redis:7.2
    container_name: paperless-redis
    restart: unless-stopped

    volumes:
      - /mnt/truenas/appdata/paperless/redis:/data

    labels:
      - "diun.enable=false"

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - db
      - redis

    user: "2001:3000"

    ports:
      - "8010:8000"

    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBNAME: ${DB_NAME}
      PAPERLESS_DBUSER: ${DB_USER}
      PAPERLESS_DBPASS: ${DB_PASSWORD}
      PAPERLESS_TIME_ZONE: ${PAPERLESS_TIME_ZONE}
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_URL: ${PAPERLESS_URL}
      PAPERLESS_CONSUMER_POLLING: "30"

    volumes:
      - /mnt/truenas/appdata/paperless/data:/usr/src/paperless/data
      - /mnt/truenas/appdata/paperless/media:/usr/src/paperless/media
      - /mnt/truenas/appdata/paperless/export:/usr/src/paperless/export
      - /mnt/truenas/appdata/paperless/consume:/usr/src/paperless/consume
      - /mnt/truenas/appdata/paperless_import_zip/export:/import


    labels:
      - "diun.enable=true"
      - homepage.group=Documents
      - homepage.id=paperless
      - homepage.name=Paperless
      - homepage.icon=paperless
      - homepage.href=http://192.168.178.122:8010
      - homepage.description=Document Management
